### ISSUE TITLE
Transfer all content from member issues to the website

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#45]
- [ ] Stephen Kovats #44 
- [x] Rana Najmaldin Mohammed #43 or #38 ?
- [x] Baby Omer #32 
- [x] Nour Fekry #40 
- [x] Nunas Eluzai #36 or #39 ?
- [x] Yaro Manyang Mawel #37 
- [x] Joyce Akello #35 
- [x] Richard Gama #34 
- [x] Yine Yenki #23 
- [x] Yine Beatrice Jale #31
- [x] Mathew Lubari #30 or #6 ?
- [x] Ayom Ruei Ayom #29 
- [x] Sunday Guido Elisa #28 
- [x] Timm Wille #26 
- [x] Lomora Ronald .md #25 
- [x] Mawa Robert #24 
- [x] Yine Yenki #23 
- [x] Andrew Wafela #22 
- [x] Kenyi Gilbert Charles #21 
- [x] Dawa Edina Hillary #20 
- [x] Maliamungu Richard #19

**Comment by timmwille** [comment]
@MartinSchott here you have an overview

**Comment by timmwille** [comment]
Shall we create the Local Expert Action Directory from this? @bmen @MartinSchott @romeoplat @yyenki @PyGamma @gibertgibs @maliarich ? → I think this is perfect so if we can speed this up and everything that is part of the repo (everything in the issues has to be transformed over to "code") → then we have everyone in here covered and can fork the Repo over to: 
https://github.com/ASKnet-Community  and rename it to **LEAD**

@bmen will give it a new structure etc.

**Comment by chardso** [comment]
We are the world,we want to read stories of each and everyone,to impact us, please complete for us stories.

**Comment by MartinSchott** [comment]
I'm ticking all the checkboxes that were content-checked by me

**Comment by bmen** [comment]
See here: https://github.com/ASKnet-Community/LEAD/issues/2
